{{- if .Values.initializerEnabled }}
apiVersion: v1
kind: Pod
metadata:
  name: {{ include "vertica-kafka-scheduler.initializer-fullname" . }}
  labels:
    vertica.com/kafka-scheduler-component: "initializer"
    {{- include "vertica-kafka-scheduler.labels" . | nindent 4 }}
spec:
  {{- with .Values.imagePullSecrets }}
  imagePullSecrets:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  serviceAccountName: {{ include "vertica-kafka-scheduler.serviceAccountName" . }}
  securityContext:
    {{- toYaml .Values.podSecurityContext | nindent 8 }}
  containers:
    - name: main
      securityContext:
        {{- toYaml .Values.securityContext | nindent 12 }}
      image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
      imagePullPolicy: {{ .Values.image.pullPolicy }}
      command:
      - sleep
      - infinity
      resources:
        {{- toYaml .Values.resources | nindent 12 }}
      volumeMounts:
      - name: vkconfig
        mountPath: /opt/vertica/packages/kafka/config
      {{- if .Values.tls.enabled }}
      {{- if .Values.tls.trustStoreSecretName }}
      - name: truststore
        mountPath: {{ .Values.tls.trustStoreMountPath }}
      {{- end }}
      {{- if .Values.tls.keyStoreSecretName }}
      - name: keystore
        mountPath: {{ .Values.tls.keyStoreMountPath }}
      {{- end }}
      {{- end }}
      env:
      - name: VKCONFIG_JVM_OPTS
        value: {{ include "vertica-kafka-scheduler.jvmOpts" . }}
      - name: VKCONFIG_CONF
        value: /opt/vertica/packages/kafka/config/vkconfig.conf
  volumes:
  - name: vkconfig
    configMap:
      name: {{ include "vertica-kafka-scheduler.configmap-fullname" . }}
  {{- if .Values.tls.enabled }}
  {{- if .Values.tls.trustStoreSecretName }}
  - name: truststore
    secret:
      secretName: {{ .Values.tls.trustStoreSecretName }}
  {{- end }}
  {{- if .Values.tls.keyStoreSecretName }}
  - name: keystore
    secret:
      secretName: {{ .Values.tls.keyStoreSecretName }}
  {{- end }}
  {{- end }}
  {{- with .Values.nodeSelector }}
  nodeSelector:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  {{- with .Values.affinity }}
  affinity:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  {{- with .Values.tolerations }}
  tolerations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
{{- end -}}
